# Generated by Django 4.1.3 on 2022-11-16 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
                ('phone_number', models.CharField(max_length=128)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('organization', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('Физическое-лицо', 'jismoniy_shaxs'), ('Юридическое-лицо', 'yuridik_shaxs')], default='yuridik_shaxs', max_length=50)),
                ('status', models.CharField(choices=[('новый', 'yangi'), ('умеренно', 'moderatsiyada'), ('подтвержденный', 'tasdiqlangan'), ('отмененный', 'bekor_qilingan')], default='yangi', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсоры',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
                ('full_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('contract', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('type', models.CharField(choices=[('бакалавр', 'bakalavr'), ('магистр', 'magistr')], max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.university')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'СтудентЫ',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='common.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.student')),
            ],
            options={
                'verbose_name': 'Спонсорство',
                'verbose_name_plural': 'Спонсорство',
                'ordering': ('-id',),
            },
        ),
    ]
