# Generated by Django 4.1.3 on 2022-11-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='user',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
