# Generated by Django 4.1.3 on 2022-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_sponsor_user_sponsor_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('yangi', 'yangi'), ('moderatsiyada', 'moderatsiyada'), ('tasdiqlangan', 'tasdiqlangan'), ('bekor_qilingan', 'bekor_qilingan')], default='yangi', max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('jismoniy_shaxs', 'jismoniy_shaxs'), ('yuridik_shaxs', 'yuridik_shaxs')], default='yuridik_shaxs', max_length=50),
        ),
    ]
