# Generated by Django 4.1.3 on 2022-11-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_sponsor_status_alter_sponsor_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('-id',), 'verbose_name': 'Homiy', 'verbose_name_plural': 'Homiylar'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='payment_type',
            field=models.CharField(choices=[('uzcard', 'uzcard'), ('humo', 'humo'), ('visa', 'visa')], default='uzcard', max_length=50),
        ),
    ]
