# Generated by Django 4.1.3 on 2022-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_sponsor_options_sponsor_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorship',
            options={'ordering': ('-id',), 'verbose_name': 'Homiylik', 'verbose_name_plural': 'Homiyliklar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-id',), 'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('-id',), 'verbose_name': 'Universitet', 'verbose_name_plural': 'Universitetlar'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.CharField(choices=[('bakalavr', 'bakalavr'), ('magistr', 'magistr')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
