# Generated by Django 4.1.3 on 2022-11-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_sponsorship_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='common.sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='common.student'),
        ),
    ]
